### ISSUE TITLE
fortunes.txt ownership?

### ISSUE THREAD

**Issue by onlyjob** [cznic/lldb#1]
[fortunes.txt](../blob/master/testdata/fortunes.txt) may be a concern due to lack of documentation of its origin, license and copyright. Please clarify.

**Comment by cznic** [comment]
Thanks for the report.

I have to first investigate the origin of this file as well as why It's not properly licensed. ATM, I have no idea. Will look into this. (Real soon now, like hopefuly tomorrow ;-)

Plan B: Delete it (and any tests depending on it.)

**Comment by onlyjob** [comment]
Thanks. :)
